### ISSUE TITLE
# in url-prefix breaking theme

### ISSUE THREAD

**Issue by Eeems** [zvuc/Aquamarine#1]
I've noticed that unless I remove the # from the url-prefix, when I load irccloud by going to https://www.irccloud.com/ the theme doesn't load.

**Comment by zvuc** [comment]
That's actually intended behavior, as I wrote in the Readme (although now that I look at it, it should have been more clear, sorry) and the userstyles page. I included the `#` in the url-prefix because I wanted to prevent the userstyle from affecting and breaking other 'non-chat' view pages with domains starting from irccloud.com (like https://www.irccloud.com/about, https://www.irccloud.com/faq etc). The main chat view always appends # after the page is loaded (and keeps it even when you reload the page), and if you're an active user you're more likely to keep IRCCloud as a pinned (app) tab so it's likely that the domain will stay the same.. hence why I decided to keep the #.

That said, if you're the type who opens up the site manually every time without keeping the tab, you are welcome to remove the # from the url-prefix, if you don't care about other pages looking weird with dark backgrounds. :)

**Comment by Eeems** [comment]
adding a # after loading the page makes it so it fails to load the theme. This technically breaks the theme for people who accidentally close the tab and then reopen. Yes I do pin the tab, but sometimes I reload it since I sometimes mess around in the console. Reloading it and having no theme until I reload a second time can be quite annoying.
Editing the url-prefix is easy enough, except since I've installed it with stylish that keeps on getting overridden when it fetches it again.

If you care about not affecting any of the pages other then the main IRC app page, there is some magic you could do with regexp() instead of url-prefix() https://developer.mozilla.org/en-US/docs/Web/CSS/@document

**Comment by zvuc** [comment]
Hmm, to think about it again, you're right it could be quite confusing for some users when they install the style and see the theme not applying when they load the page the first time..

Instead of using regexp though, I think a simpler way would be just set the url-prefix to #-less domain and prepend `body.app` to all the classes so that it only applies to the chat view page. Thanks for the suggestion. :)

**Comment by Eeems** [comment]
No problem <3
